Reset display of editor images
woocommerce/storefront pull request #1256
Opened 2020-02-11 15:36 UTC by Aljullu

Fixes #1255. It centers the inner block image in the _Cart_ block.

![imatge](https://user-images.githubusercontent.com/3616980/74251560-9d1ae600-4cec-11ea-8eda-b7b130bd0656.png)

This change will affect all images in the editor. I did some basic testing and everything was looking good to me, but we might consider deferring merging this PR until the next version of Storefront is released so we give more time for testing.

## Steps to test
1. Install the last version of Gutenberg and the dev version of WooCommerce Blocks.
2. Add a _Cart_ block and switch to the _Empty Cart_ view.
3. Verify the image is centered by default.

2020-02-20 09:49 UTC, senadir commented on assets/css/base/gutenberg-editor.scss
> -	display: block;
Isn’t this change a bit wildcard and might affect all image blocks? would it make sense to scope to cart only?

2020-02-20 09:50 UTC, senadir requested changes
yeah after testing this change does break other blocks like the Image block
![image](https://user-images.githubusercontent.com/6165348/74921937-c6173700-53ce-11ea-8393-1018b2568622.png)

2020-02-20 10:09 UTC, senadir commented
also, changes here might contradict with https://github.com/woocommerce/storefront/pull/1265

2020-02-20 12:47 UTC, Aljullu commented
> yeah after testing this change does break other blocks like the Image block

I'm unable to reproduce this. Is that with a specific version of Gutenberg or WP? :thinking: 

> Isn’t this change a bit wildcard and might affect all image blocks?

Yeah... I'm fine closing this PR and going with something more local. I still think, however, that forcing all images to `display: block;` will continuously bring issues like #1255 and #1263, because upstream projects rely on browser default styles and we are overriding those. So we will need to continuously add exceptions to that override.

> also, changes here might contradict with #1265

Right, I think #1265 wouldn't have been needed if we didn't set the `display` of all images to `block`.

2020-04-16 04:07 UTC, haszari commented
Marking this as blocked until we wrap up the discussion on #1297:  https://github.com/woocommerce/storefront/pull/1297#issuecomment-614403990

2020-08-27 07:29 UTC, Aljullu commented
Closing this PR since #1255 was fixed in WC Blocks.

2020-08-27 07:29 UTC, closed without merging