Fix editor alignment issues
woocommerce/storefront pull request #1897
Opened 2022-02-07 16:20 UTC by DustinHartzler

Fixes #1320 

There were a couple of heading blocks and blockquote blocks that did not align with the rest of the text in the editor. Added `rem` to a couple of the calculations and change the blockquotes to have a left/right margin of `auto`

### Screenshots

**Here's the before:**
![alignment-before](https://user-images.githubusercontent.com/2293077/152827198-a0c445da-0c40-4493-8c7d-62eba7b45522.png)

**After**
![alignment-after](https://user-images.githubusercontent.com/2293077/152827318-931204aa-6326-4cdc-82b8-56a714947af0.png)

### How to test the changes in this Pull Request:

1. Build the theme and install
2. Add different heading types (H1, H2, etc) and blockquotes
3. The should all have the same left justification

- No flows are affected

### Changelog

> Fix – Left justified heading and blockquote elements. #1320

2022-02-09 14:52 UTC, tomasztunik requested changes
Hey Dustin, thanks for picking this one up! It was small but definitely annoying bugger! I've added couple notes to enable us to merge this. Would appreciate if you could have another look at it!

I believe the suggestion from https://github.com/woocommerce/storefront/issues/1320#issuecomment-868549528 in `/assets/css/base/gutenberg-editor.scss:L303-310` might be the best bet here. 
I believe we should be able to get around it without using !important there. As it was suggested as a mean to override current broken settings.

Was looking at changing modular scale base from em to rem but altering it will affect vertical rhythm of the pages too much as it would affect every ms() function usage. On top of it there seems to be a bug and even though ms() function should accept custom bases locally so we use it only for max-width on blocks it refuses to work 🤷 

I have confirmed that this issue is local to storefront theme.

2022-02-09 14:52 UTC, tomasztunik commented on assets/css/base/gutenberg-blocks.scss
> +		margin: 0 auto;
You have removed accidentally bottom margin here causing blockquote to "stick" to the next block that follows it. Also let's change it to `margin-bottom: ms(2);` to avoid it overriding .wp-block sytles for horizontal margins

2022-02-09 14:52 UTC, tomasztunik commented on assets/css/base/gutenberg-editor.scss
> +	max-width: ms(19) rem;
This would produce invalid css and _fix it_ by doing so - it would fall back to default values that produce "better" ux but not matching storefront frontend. We'll need to remove it.

![Screenshot 2022-02-09 at 14 56 07](https://user-images.githubusercontent.com/112270/153215524-4a236d1e-6f7d-4a20-b123-bd99b36d0258.jpg)

2022-02-09 14:52 UTC, tomasztunik commented on assets/css/sass/utils/_variables.scss
> +$container-width:   ms(18) rem;
Same case here, this will produce invalid CSS and calculations.

2022-02-23 17:40 UTC, DustinHartzler commented
Thanks @tomasztunik for the feedback. CSS isn't my area of expertise, but this bug was driving me crazy!

I've tested the above changes on one of my test sites and the headers are now left justified with the rest of the text 🎉

2022-02-24 15:15 UTC, gigitux requested changes
Thanks for working on this! 🙏 

I suggest to add a comment about the fix and at this moment there are lint errors. This is the command for fix them:

```
npm run lint:css-fix
```

2022-02-24 15:15 UTC, gigitux commented on assets/css/base/gutenberg-editor.scss
>  // Main content width
What do you think if we add a comment about this fix here? For example in this way:
```suggestion
// Main content width
// These two rules are copied from https://github.com/woocommerce/storefront/issues/1320#issuecomment-868549528
```

See these numbers so specific, it is a rare thing, so I guess that it is better to give a little bit of context

2022-03-04 14:56 UTC, sunyatasattva approved these changes
Personally, I feel the solution is really convoluted with those weird numbers. Thanks @gigitux for adding the comment at least it explains some context.

I still wish there was a better way, but as a patch, I suppose it is fine.

2022-03-04 16:21 UTC, merged